VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "Equipments"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Compare Database

Public ModelNumber As String
Public Description As String
Public AssetNumber As String
Public EquipmentNumber As String
Public SerialNumber As String
'Public Location As String
'Public Note As String
'Public Service As Boolean
'Public SafetyIntstruction As String
Public PM As String
'Public Saftey As String
Public DateRegistered As Date
Public ID As Long
Public Edit As Boolean
'Public GNoteID As Integer
Public EquipmentType As String
Public Manufacturer As String
Public Status As String
Public System As String


