VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "GeneralNote"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Compare Database

Public ID As Integer
Public Title As String
Public Description As String
Public Date_ As Date
'Public User As String
Public Comment As String
Public Edit As Boolean



