VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "PMTask"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Compare Database

'Public PMTaskName As String
'Public PMType As String
Public Description As String
Public AssignedTo As String
Public FrequencyDays As String

Public Edit As Boolean
Public ID As Integer




