VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "WO"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Compare Database

Public WOID As Integer
Public WODescription As String
Public ModelNumber As String
Public Scheduled As Boolean
Public WOType As String
Public WORequest As String
Public AssignedTo As String
Public Status As String
Public Priority As String
Public Edit As Boolean

